### ISSUE TITLE
Passing relative paths from command line doesn't work in Slic3r

### ISSUE THREAD

**Issue by xoan** [ctemescw/meikian-dev#28]
```
user@meikian:~$ pwd
/home/user
user@meikian:~$ ls cube.stl
cube.stl
user@meikian:~$ slic3r --info cube.stl
Failed to open cube.stl
user@meikian:~$ slic3r --info /home/user/cube.stl
Info about cube.stl:
  size:              x=20.000 y=20.000 z=10.000
  number of facets:  12
  number of shells:  1
  volume:            4000.000
  needed repair:     no
```

Absolute paths works, but relative ones doesn't.

```
$ cat /usr/local/bin/slic3r
#!/bin/bash

SLIC3R_DIR=/usr/local/share/slic3r

cd ${SLIC3R_DIR}/bin
./slic3r "${@}"
```

I guess `cd` in launcher script breaks relative paths from current working directory passing it to SLIC3R_DIR.

**Comment by ctemescw** [comment]
Fixed the call to the Slic3r binary in the launcher script.

**Comment by luipir** [comment]
hmmm... va a ser dificil hacer beackports o reverse de commit si el bug no vien relalcionado con el codigo modificado.

@ctemescw  encontraste una manera de enlazar el codigo de preparación de la distribución con los bugs?

ciao

**Comment by ctemescw** [comment]
Buenas noches Gino,

Una distribución es muy diferente a un programa en tanto que hay muchos
elementos que no están alojados en el propio sistema de control de
versiones.

En este caso el problema estaba en el script que se usa para lanzar Slic3r
en Meikian, pero ese script está dentro del propio paquete, no tiene nada
que ver con el sistema de creación de la distro.


Un saludo,
Carlos

**Comment by luipir** [comment]
vale entiendo... asi' que para tener traza, seria bueno tener una docker donde instalar todo y registrar los cambio... es solo una idea

**Comment by ctemescw** [comment]
No le veo razón de ser. Los cambios que hago en los paquetes que hago o
modifico los registro en el changelog del paquete correspondiente y los
cambios en las versiones de los paquetes que lleva cada versión de meikian
los tengo registrados en la máquina en la que las genero. Algo más del 95%
de los paquetes que lleva una iso de Meikian son paquetes estándar de los
repositorios de Debian, paquetes que yo no toco para nada.

Docker en mi caso no me aporta nada excepto tener que ponerme a mirar otra
tecnología de virtualización más. Tal y como lo tengo montado todo
actualmente con kvm, me cubre las necesidades de Meikian y además ya tengo
muy trillado el funcionamiento y el flujo de trabajo.

Gracias de todas maneras por los comentarios :)

Un saludo,
Carlos


2015-03-08 21:48 GMT+01:00 Luigi Pirelli <notifications@github.com>:
